# Generated by Django 2.2.8 on 2019-12-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='Yaxsi kitabdir!', verbose_name='Aciqlama'),
        ),
    ]
