# Generated by Django 2.2.8 on 2019-12-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20191217_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True, verbose_name='Mehsul')),
                ('description', models.TextField(default='Yaxsi mehsuldur!', max_length=500, verbose_name='Aciqlama')),
                ('category', models.IntegerField(choices=[(1, 'Convenience Goods'), (2, 'Shopping Goods'), (3, 'Specialty Good')], default=1)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products/images ', verbose_name='Sekil')),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Qiymeti')),
                ('production_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_new', models.BooleanField(blank=True, default=0, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='products/files', verbose_name='Sened')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=1, verbose_name='Reytinq')),
                ('detailed_view_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'company_products',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['price'], 'verbose_name': 'Kitab', 'verbose_name_plural': 'Kitablar'},
        ),
    ]
